# Generated by Django 3.0 on 2019-12-18 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0002_remove_profile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xPos', models.IntegerField()),
                ('yPos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardLocationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.BoardLocation')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.ManyToManyField(through='jeu.BoardLocationState', to='jeu.BoardLocation')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jeu.BoardLocation')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jeu.BoardLocation')),
            ],
        ),
        migrations.AddField(
            model_name='boardlocationstate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.GameState'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gameState',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeu.GameState'),
        ),
    ]
