# Generated by Django 3.0 on 2019-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0003_auto_20191218_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardlocationstate',
            old_name='state',
            new_name='gameState',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='player2',
            new_name='player0',
        ),
        migrations.AddField(
            model_name='boardlocationstate',
            name='playerState',
            field=models.IntegerField(default=-8),
        ),
    ]
