# Generated by Django 3.0 on 2019-12-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0004_auto_20191218_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='player0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jeu.BoardLocation'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jeu.BoardLocation'),
        ),
    ]
