# Generated by Django 3.0 on 2019-12-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0005_auto_20191218_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='nbDemiTour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='playerNum',
            field=models.IntegerField(null=True),
        ),
    ]
